// ============================================================
// TOKI · Aprende a decirlo
// © 2026 Diego Aroca. Todos los derechos reservados.
// Las 1000 frases para tu vida
// ============================================================

// TOKI — Las 1000 frases para tu vida
// 12 áreas × 5 niveles × 3 tipos (flu, frases, sit)

export const AREAS = [
  { id:'seguridad', n:'Seguridad', ic:'🛡️', ess:1 },
  { id:'salud', n:'Salud', ic:'🏥', ess:1 },
  { id:'necesidades', n:'Necesidades', ic:'🍽️', ess:1 },
  { id:'compras', n:'Compras', ic:'🛒' },
  { id:'transporte', n:'Transporte', ic:'🚌' },
  { id:'restaurante', n:'Restaurante', ic:'🍔' },
  { id:'relaciones', n:'Relaciones', ic:'🤝' },
  { id:'sentimientos', n:'Sentimientos', ic:'💛' },
  { id:'colegio', n:'Colegio', ic:'📚' },
  { id:'ocio', n:'Ocio', ic:'🎮' },
  { id:'tecnologia', n:'Tecnología', ic:'📱' },
  { id:'casa', n:'Casa', ic:'🏠' },
];

export const EX = [

// 🛡️ SEGURIDAD
{id:'se001',a:'seguridad',ty:'flu',lv:1,ph:'Ayuda',em:'🆘'},
{id:'se002',a:'seguridad',ty:'flu',lv:1,ph:'Socorro',em:'🆘'},
{id:'se003',a:'seguridad',ty:'flu',lv:1,ph:'Ven aquí',em:'📢'},
{id:'se004',a:'seguridad',ty:'flu',lv:1,ph:'Para',em:'✋'},
{id:'se005',a:'seguridad',ty:'flu',lv:1,ph:'No quiero',em:'🚫'},
{id:'se006',a:'seguridad',ty:'flu',lv:1,ph:'Mamá',em:'📞'},
{id:'se007',a:'seguridad',ty:'flu',lv:1,ph:'Papá',em:'📞'},
{id:'se008',a:'seguridad',ty:'frases',lv:1,q:'¿Cómo pides ayuda?',fu:'Ayuda por favor',em:'🆘'},
{id:'se009',a:'seguridad',ty:'flu',lv:2,ph:'Necesito ayuda',em:'📞'},
{id:'se010',a:'seguridad',ty:'flu',lv:2,ph:'Estoy perdido',em:'📍'},
{id:'se011',a:'seguridad',ty:'flu',lv:2,ph:'Eso no me gusta',em:'🚫'},
{id:'se012',a:'seguridad',ty:'flu',lv:2,ph:'No quiero ir contigo',em:'🚫'},
{id:'se013',a:'seguridad',ty:'flu',lv:2,ph:'Déjame en paz',em:'✋'},
{id:'se014',a:'seguridad',ty:'flu',lv:2,ph:'No me toques',em:'✋'},
{id:'se015',a:'seguridad',ty:'flu',lv:2,ph:'Eso me da miedo',em:'😨'},
{id:'se016',a:'seguridad',ty:'flu',lv:2,ph:'No es mío',em:'🚫'},
{id:'se017',a:'seguridad',ty:'frases',lv:2,q:'Estás perdido y necesitas ayuda. ¿Qué dices?',fu:'Estoy perdido necesito ayuda',em:'📍'},
{id:'se018',a:'seguridad',ty:'frases',lv:2,q:'No quieres ir con alguien. ¿Qué dices?',fu:'No quiero ir contigo',em:'🚫'},
{id:'se019',a:'seguridad',ty:'sit',lv:2,si:'Un desconocido te ofrece subir a su coche',su:'No gracias no te conozco',op:['No gracias no te conozco','Vale vamos','Tengo hambre'],em:'🚗'},
{id:'se020',a:'seguridad',ty:'sit',lv:2,si:'Hay fuego en la cocina',su:'Fuego salid de aquí',op:['Fuego salid de aquí','Qué bonito','Tengo frío'],em:'🔥'},
{id:'se021',a:'seguridad',ty:'sit',lv:2,si:'Alguien te empuja en el patio',su:'No me empujes eso no está bien',op:['No me empujes','Vale','No pasa nada'],em:'😠'},
{id:'se022',a:'seguridad',ty:'flu',lv:3,ph:'Socorro ayuda por favor',em:'🆘'},
{id:'se023',a:'seguridad',ty:'flu',lv:3,ph:'No te conozco déjame',em:'🚫'},
{id:'se024',a:'seguridad',ty:'flu',lv:3,ph:'Llama a mis padres',em:'📞'},
{id:'se025',a:'seguridad',ty:'flu',lv:3,ph:'Me he hecho daño',em:'🩹'},
{id:'se026',a:'seguridad',ty:'flu',lv:3,ph:'Eso es peligroso no lo hagas',em:'⚠️'},
{id:'se027',a:'seguridad',ty:'flu',lv:3,ph:'No vayas por ahí es peligroso',em:'⚠️'},
{id:'se028',a:'seguridad',ty:'frases',lv:3,q:'¿Cómo dices tu número de teléfono?',fu:'Mi teléfono es el...',em:'📱'},
{id:'se029',a:'seguridad',ty:'frases',lv:3,q:'Te has cortado. ¿Qué dices?',fu:'Me he cortado necesito una tirita',em:'🩹'},
{id:'se030',a:'seguridad',ty:'sit',lv:3,si:'Alguien te toca y no quieres',su:'No me toques eso no me gusta',op:['No me toques eso no me gusta','Vale','No pasa nada'],em:'✋'},
{id:'se031',a:'seguridad',ty:'sit',lv:3,si:'Un compañero te quita las cosas',su:'Eso es mío devuélvemelo',op:['Eso es mío devuélvemelo','Vale','No importa'],em:'😠'},
{id:'se032',a:'seguridad',ty:'sit',lv:3,si:'Alguien te dice que hagas algo malo',su:'No voy a hacer eso está mal',op:['No voy a hacer eso','Bueno vale','No sé'],em:'🚫'},
{id:'se033',a:'seguridad',ty:'flu',lv:4,ph:'Necesito llamar a mis padres',em:'📞'},
{id:'se034',a:'seguridad',ty:'flu',lv:4,ph:'Vivo en la calle... número...',em:'🏠'},
{id:'se035',a:'seguridad',ty:'flu',lv:4,ph:'No voy a hacer eso porque es peligroso',em:'⚠️'},
{id:'se036',a:'seguridad',ty:'flu',lv:4,ph:'Voy a llamar a alguien para que me ayude',em:'📞'},
{id:'se037',a:'seguridad',ty:'frases',lv:4,q:'Te has perdido. ¿Qué le dices a un policía?',fu:'Me he perdido necesito ir a casa',em:'👮'},
{id:'se038',a:'seguridad',ty:'sit',lv:4,si:'Alguien te pide hacer algo que no quieres',su:'No quiero hacer eso déjame en paz',op:['No quiero hacer eso déjame en paz','Bueno vale','No sé'],em:'✋'},
{id:'se039',a:'seguridad',ty:'sit',lv:4,si:'Un amigo se ha caído y se ha hecho mucho daño',su:'Espera aquí voy a pedir ayuda',op:['Voy a pedir ayuda','Adiós','No sé'],em:'🩹'},
{id:'se040',a:'seguridad',ty:'flu',lv:5,ph:'Me he perdido y necesito que alguien me ayude a llegar a casa',em:'📍'},
{id:'se041',a:'seguridad',ty:'flu',lv:5,ph:'Hay una persona que me está siguiendo y tengo miedo',em:'😨'},
{id:'se042',a:'seguridad',ty:'frases',lv:5,q:'¿Cómo explicas tu dirección?',fu:'Vivo en Murcia en la calle... número...',em:'🏠'},

// 🏥 SALUD
{id:'sa001',a:'salud',ty:'flu',lv:1,ph:'Me duele',em:'🤕'},
{id:'sa002',a:'salud',ty:'flu',lv:1,ph:'Estoy malo',em:'🤒'},
{id:'sa003',a:'salud',ty:'flu',lv:1,ph:'Tengo tos',em:'🤧'},
{id:'sa004',a:'salud',ty:'flu',lv:1,ph:'Estoy bien',em:'😊'},
{id:'sa005',a:'salud',ty:'flu',lv:1,ph:'Pupa',em:'🩹'},
{id:'sa006',a:'salud',ty:'frases',lv:1,q:'Te duele mucho algo. ¿Qué dices?',fu:'Me duele mucho aquí',em:'🤕'},
{id:'sa007',a:'salud',ty:'flu',lv:2,ph:'Me duele la barriga',em:'🤕'},
{id:'sa008',a:'salud',ty:'flu',lv:2,ph:'Me duele la cabeza',em:'🤕'},
{id:'sa009',a:'salud',ty:'flu',lv:2,ph:'Me duele la espalda',em:'🤕'},
{id:'sa010',a:'salud',ty:'flu',lv:2,ph:'Me pica mucho aquí',em:'🤕'},
{id:'sa011',a:'salud',ty:'flu',lv:2,ph:'Necesito mi pastilla',em:'💊'},
{id:'sa012',a:'salud',ty:'flu',lv:2,ph:'No veo bien',em:'👓'},
{id:'sa013',a:'salud',ty:'flu',lv:2,ph:'Me sangra la nariz',em:'🩸'},
{id:'sa014',a:'salud',ty:'flu',lv:2,ph:'Tengo mocos',em:'🤧'},
{id:'sa015',a:'salud',ty:'flu',lv:2,ph:'Me duele la muela',em:'🦷'},
{id:'sa016',a:'salud',ty:'flu',lv:2,ph:'Me duele el oído',em:'👂'},
{id:'sa017',a:'salud',ty:'frases',lv:2,q:'No te encuentras bien. ¿Qué dices?',fu:'No me encuentro bien',em:'🤒'},
{id:'sa018',a:'salud',ty:'frases',lv:2,q:'Necesitas tu pastilla. ¿Qué dices?',fu:'Tengo que tomar mi pastilla',em:'💊'},
{id:'sa019',a:'salud',ty:'sit',lv:2,si:'Te duele mucho la barriga',su:'Me duele la barriga',op:['Me duele la barriga','Quiero jugar','Estoy contento'],em:'🏥'},
{id:'sa020',a:'salud',ty:'sit',lv:2,si:'Te has caído y te sangra la rodilla',su:'Me he caído y me sangra',op:['Me he caído y me sangra','Estoy bien','Quiero jugar'],em:'🩹'},
{id:'sa021',a:'salud',ty:'flu',lv:3,ph:'Me tengo que lavar los dientes',em:'🪥'},
{id:'sa022',a:'salud',ty:'flu',lv:3,ph:'Me he hecho daño en la rodilla',em:'🩹'},
{id:'sa023',a:'salud',ty:'flu',lv:3,ph:'Creo que tengo fiebre',em:'🤒'},
{id:'sa024',a:'salud',ty:'flu',lv:3,ph:'Me duele mucho la garganta',em:'🤕'},
{id:'sa025',a:'salud',ty:'flu',lv:3,ph:'Necesito sentarme un momento',em:'😫'},
{id:'sa026',a:'salud',ty:'flu',lv:3,ph:'Me mareo un poco',em:'😵'},
{id:'sa027',a:'salud',ty:'flu',lv:3,ph:'Me he quemado con el agua',em:'🔥'},
{id:'sa028',a:'salud',ty:'flu',lv:3,ph:'Se me ha metido algo en el ojo',em:'👁️'},
{id:'sa029',a:'salud',ty:'frases',lv:3,q:'Te has caído y te duele. ¿Qué dices?',fu:'Me he caído y me duele la pierna',em:'🩹'},
{id:'sa030',a:'salud',ty:'frases',lv:3,q:'Crees que tienes fiebre. ¿Qué dices?',fu:'Creo que tengo fiebre estoy caliente',em:'🤒'},
{id:'sa031',a:'salud',ty:'sit',lv:3,si:'Llevas mucho sin lavarte los dientes',su:'Voy a lavarme los dientes',op:['Voy a lavarme los dientes','No quiero','Mañana'],em:'🪥'},
{id:'sa032',a:'salud',ty:'sit',lv:3,si:'Te sientes mareado en clase',su:'Me estoy mareando necesito salir',op:['Me estoy mareando','Estoy bien','Quiero jugar'],em:'😵'},
{id:'sa033',a:'salud',ty:'flu',lv:4,ph:'Necesito ducharme antes de cenar',em:'🚿'},
{id:'sa034',a:'salud',ty:'flu',lv:4,ph:'Me encuentro muy mal necesito un médico',em:'🏥'},
{id:'sa035',a:'salud',ty:'flu',lv:4,ph:'Soy alérgico a eso no puedo comerlo',em:'⚠️'},
{id:'sa036',a:'salud',ty:'flu',lv:4,ph:'Me he tomado la pastilla esta mañana',em:'💊'},
{id:'sa037',a:'salud',ty:'frases',lv:4,q:'Estás muy mal. ¿Qué dices?',fu:'No puedo más necesito ir al médico',em:'🏥'},
{id:'sa038',a:'salud',ty:'sit',lv:4,si:'Te ofrecen comida y eres alérgico',su:'No puedo comer eso soy alérgico',op:['No puedo soy alérgico','Sí gracias','No sé'],em:'⚠️'},
{id:'sa039',a:'salud',ty:'flu',lv:5,ph:'Me duele mucho la barriga desde esta mañana y no se me pasa',em:'🤕'},
{id:'sa040',a:'salud',ty:'flu',lv:5,ph:'Necesito que me lleven al médico porque no me encuentro nada bien',em:'🏥'},

// 🍽️ NECESIDADES
{id:'ne001',a:'necesidades',ty:'flu',lv:1,ph:'Tengo hambre',em:'🍕'},
{id:'ne002',a:'necesidades',ty:'flu',lv:1,ph:'Quiero agua',em:'💧'},
{id:'ne003',a:'necesidades',ty:'flu',lv:1,ph:'Tengo frío',em:'🥶'},
{id:'ne004',a:'necesidades',ty:'flu',lv:1,ph:'Tengo calor',em:'🥵'},
{id:'ne005',a:'necesidades',ty:'flu',lv:1,ph:'Tengo sueño',em:'😴'},
{id:'ne006',a:'necesidades',ty:'flu',lv:1,ph:'Quiero pan',em:'🍞'},
{id:'ne007',a:'necesidades',ty:'flu',lv:1,ph:'Más agua',em:'💧'},
{id:'ne008',a:'necesidades',ty:'flu',lv:1,ph:'Tengo sed',em:'💧'},
{id:'ne009',a:'necesidades',ty:'flu',lv:1,ph:'No quiero',em:'🚫'},
{id:'ne010',a:'necesidades',ty:'frases',lv:1,q:'¿Cómo dices que tienes mucha hambre?',fu:'Tengo mucha hambre',em:'🍕'},
{id:'ne011',a:'necesidades',ty:'frases',lv:1,q:'¿Cómo dices que tienes mucha sed?',fu:'Tengo mucha sed',em:'💧'},
{id:'ne012',a:'necesidades',ty:'flu',lv:2,ph:'Tengo mucho sueño',em:'😴'},
{id:'ne013',a:'necesidades',ty:'flu',lv:2,ph:'Necesito ir al baño',em:'🚻'},
{id:'ne014',a:'necesidades',ty:'flu',lv:2,ph:'Quiero comer algo',em:'🍽️'},
{id:'ne015',a:'necesidades',ty:'flu',lv:2,ph:'No quiero más comida',em:'🍽️'},
{id:'ne016',a:'necesidades',ty:'flu',lv:2,ph:'Dame una manta',em:'🥶'},
{id:'ne017',a:'necesidades',ty:'flu',lv:2,ph:'Abre la ventana',em:'🥵'},
{id:'ne018',a:'necesidades',ty:'flu',lv:2,ph:'Quiero leche',em:'🥛'},
{id:'ne019',a:'necesidades',ty:'flu',lv:2,ph:'Esto no me gusta',em:'👎'},
{id:'ne020',a:'necesidades',ty:'flu',lv:2,ph:'Quiero más',em:'🍽️'},
{id:'ne021',a:'necesidades',ty:'flu',lv:2,ph:'Ya no quiero más',em:'🍽️'},
{id:'ne022',a:'necesidades',ty:'flu',lv:2,ph:'Tengo mucha hambre',em:'🍕'},
{id:'ne023',a:'necesidades',ty:'flu',lv:2,ph:'Me quiero sentar',em:'🪑'},
{id:'ne024',a:'necesidades',ty:'frases',lv:2,q:'¿Cómo pides un vaso de agua?',fu:'Me das un vaso de agua',em:'💧'},
{id:'ne025',a:'necesidades',ty:'frases',lv:2,q:'¿Cómo dices que necesitas ir al baño?',fu:'Necesito ir al baño',em:'🚻'},
{id:'ne026',a:'necesidades',ty:'frases',lv:2,q:'Tienes mucho frío. ¿Qué pides?',fu:'Tengo frío dame una manta',em:'🥶'},
{id:'ne027',a:'necesidades',ty:'frases',lv:2,q:'No quieres comer más. ¿Qué dices?',fu:'No quiero más comida gracias',em:'🍽️'},
{id:'ne028',a:'necesidades',ty:'sit',lv:2,si:'Tienes mucha sed en el parque',su:'Podemos comprar agua tengo mucha sed',op:['Podemos comprar agua','Quiero dormir','Estoy bien'],em:'🥤'},
{id:'ne029',a:'necesidades',ty:'flu',lv:3,ph:'Quiero comer algo por favor',em:'🍽️'},
{id:'ne030',a:'necesidades',ty:'flu',lv:3,ph:'Necesito ir al baño rápido',em:'🚻'},
{id:'ne031',a:'necesidades',ty:'flu',lv:3,ph:'Me he manchado la camiseta',em:'👕'},
{id:'ne032',a:'necesidades',ty:'flu',lv:3,ph:'Necesito cambiarme de ropa',em:'👕'},
{id:'ne033',a:'necesidades',ty:'flu',lv:3,ph:'Se me ha caído al suelo',em:'😔'},
{id:'ne034',a:'necesidades',ty:'flu',lv:3,ph:'Esto está muy caliente',em:'🔥'},
{id:'ne035',a:'necesidades',ty:'flu',lv:3,ph:'No me cabe el zapato',em:'👟'},
{id:'ne036',a:'necesidades',ty:'flu',lv:3,ph:'Necesito unas tijeras',em:'✂️'},
{id:'ne037',a:'necesidades',ty:'frases',lv:3,q:'Tienes frío y necesitas un jersey. ¿Qué dices?',fu:'Tengo frío necesito un jersey',em:'🥶'},
{id:'ne038',a:'necesidades',ty:'frases',lv:3,q:'Te has manchado la camiseta. ¿Qué dices?',fu:'Me he manchado necesito cambiarme',em:'👕'},
{id:'ne039',a:'necesidades',ty:'sit',lv:3,si:'Ya es muy tarde y tienes mucho sueño',su:'Tengo mucho sueño me quiero ir a dormir',op:['Tengo sueño me quiero dormir','Quiero jugar más','No tengo sueño'],em:'😴'},
{id:'ne040',a:'necesidades',ty:'sit',lv:3,si:'La comida está muy caliente',su:'Esto está muy caliente no puedo comerlo',op:['Está muy caliente','Me da igual','Quiero más'],em:'🔥'},
{id:'ne041',a:'necesidades',ty:'flu',lv:4,ph:'Me puedes poner más comida por favor',em:'🍽️'},
{id:'ne042',a:'necesidades',ty:'flu',lv:4,ph:'No me gusta esto hay otra cosa',em:'🍽️'},
{id:'ne043',a:'necesidades',ty:'flu',lv:4,ph:'Necesito mis gafas no veo nada',em:'👓'},
{id:'ne044',a:'necesidades',ty:'frases',lv:4,q:'Quieres repetir de comida. ¿Qué dices?',fu:'Me puedes poner más que tengo hambre',em:'🍕'},
{id:'ne045',a:'necesidades',ty:'sit',lv:4,si:'No te gusta la comida',su:'Esto no me gusta hay otra cosa para comer',op:['Hay otra cosa para comer','Me da igual','Adiós'],em:'🍽️'},
{id:'ne046',a:'necesidades',ty:'flu',lv:5,ph:'Tengo mucha hambre porque hoy no he merendado',em:'🍕'},
{id:'ne047',a:'necesidades',ty:'flu',lv:5,ph:'Necesito ir al baño pero no sé dónde está',em:'🚻'},

// 🛒 COMPRAS
{id:'co001',a:'compras',ty:'flu',lv:2,ph:'Cuánto cuesta',em:'🏷️'},
{id:'co002',a:'compras',ty:'flu',lv:2,ph:'Quiero esto',em:'🛒'},
{id:'co003',a:'compras',ty:'flu',lv:2,ph:'Quiero ese',em:'👆'},
{id:'co004',a:'compras',ty:'flu',lv:2,ph:'Es muy caro',em:'💶'},
{id:'co005',a:'compras',ty:'flu',lv:2,ph:'Me lo llevo',em:'🛍️'},
{id:'co006',a:'compras',ty:'frases',lv:2,q:'Quieres saber el precio. ¿Qué preguntas?',fu:'Cuánto cuesta esto',em:'🏷️'},
{id:'co007',a:'compras',ty:'flu',lv:3,ph:'Quiero pagar con tarjeta',em:'💳'},
{id:'co008',a:'compras',ty:'flu',lv:3,ph:'Me lo puedo llevar',em:'🛍️'},
{id:'co009',a:'compras',ty:'flu',lv:3,ph:'Tiene otro color',em:'👕'},
{id:'co010',a:'compras',ty:'flu',lv:3,ph:'Dónde están los juguetes',em:'🧸'},
{id:'co011',a:'compras',ty:'flu',lv:3,ph:'Necesito una bolsa',em:'🛍️'},
{id:'co012',a:'compras',ty:'flu',lv:3,ph:'Me llevo este gracias',em:'🛒'},
{id:'co013',a:'compras',ty:'flu',lv:3,ph:'Tiene otra talla más grande',em:'👕'},
{id:'co014',a:'compras',ty:'flu',lv:3,ph:'Esto es muy bonito',em:'😍'},
{id:'co015',a:'compras',ty:'flu',lv:3,ph:'Puedo probármelo',em:'👕'},
{id:'co016',a:'compras',ty:'frases',lv:3,q:'Quieres pagar con tarjeta. ¿Qué dices?',fu:'Quiero pagar con tarjeta por favor',em:'💳'},
{id:'co017',a:'compras',ty:'frases',lv:3,q:'Quieres otra talla. ¿Qué preguntas?',fu:'Tiene esto en otra talla',em:'👕'},
{id:'co018',a:'compras',ty:'frases',lv:3,q:'Buscas los juguetes. ¿Qué preguntas?',fu:'Perdone dónde están los juguetes',em:'🧸'},
{id:'co019',a:'compras',ty:'sit',lv:3,si:'Quieres comprar un helado',su:'Quiero un helado de chocolate',op:['Quiero un helado de chocolate','Adiós','Tengo frío'],em:'🍦'},
{id:'co020',a:'compras',ty:'sit',lv:3,si:'No encuentras lo que buscas',su:'Perdone dónde están los cereales',op:['Dónde están los cereales','No sé','Adiós'],em:'🔍'},
{id:'co021',a:'compras',ty:'sit',lv:3,si:'Quieres comprar un regalo para tu madre',su:'Quiero comprar un regalo para mi madre',op:['Quiero un regalo para mi madre','Adiós','No sé'],em:'🎁'},
{id:'co022',a:'compras',ty:'flu',lv:4,ph:'Me puede cobrar esto por favor',em:'🏷️'},
{id:'co023',a:'compras',ty:'flu',lv:4,ph:'Esto no es lo que he pedido',em:'🔄'},
{id:'co024',a:'compras',ty:'flu',lv:4,ph:'Me puede dar una bolsa por favor',em:'🛍️'},
{id:'co025',a:'compras',ty:'flu',lv:4,ph:'Estoy buscando algo para regalar',em:'🎁'},
{id:'co026',a:'compras',ty:'flu',lv:4,ph:'Me puede envolver esto para regalo',em:'🎁'},
{id:'co027',a:'compras',ty:'frases',lv:4,q:'Algo está roto. ¿Qué dices?',fu:'Quiero cambiar esto porque está roto',em:'🔄'},
{id:'co028',a:'compras',ty:'sit',lv:4,si:'Te cobran más de lo que dice',su:'Perdone esto pone que cuesta menos',op:['Esto pone que cuesta menos','Vale','No sé'],em:'🏷️'},
{id:'co029',a:'compras',ty:'flu',lv:5,ph:'Quiero devolver esto porque no me vale y que me devuelvan el dinero',em:'🔄'},
{id:'co030',a:'compras',ty:'flu',lv:5,ph:'Perdone estoy buscando un regalo para mi madre y no sé qué comprar',em:'🎁'},

// 🚌 TRANSPORTE
{id:'tr001',a:'transporte',ty:'flu',lv:2,ph:'Quiero ir a casa',em:'🏠'},
{id:'tr002',a:'transporte',ty:'flu',lv:2,ph:'Dónde está el baño',em:'🚻'},
{id:'tr003',a:'transporte',ty:'flu',lv:2,ph:'Vamos a casa',em:'🏠'},
{id:'tr004',a:'transporte',ty:'flu',lv:2,ph:'Estamos lejos',em:'🗺️'},
{id:'tr005',a:'transporte',ty:'flu',lv:2,ph:'Ya llegamos',em:'✅'},
{id:'tr006',a:'transporte',ty:'frases',lv:2,q:'Necesitas encontrar el baño. ¿Qué preguntas?',fu:'Dónde está el baño',em:'🚻'},
{id:'tr007',a:'transporte',ty:'flu',lv:3,ph:'Quiero ir a casa por favor',em:'🏠'},
{id:'tr008',a:'transporte',ty:'flu',lv:3,ph:'Este autobús va al centro',em:'🚌'},
{id:'tr009',a:'transporte',ty:'flu',lv:3,ph:'Dónde está la parada',em:'🚏'},
{id:'tr010',a:'transporte',ty:'flu',lv:3,ph:'Cuánto falta para llegar',em:'⏰'},
{id:'tr011',a:'transporte',ty:'flu',lv:3,ph:'Ya hemos llegado',em:'✅'},
{id:'tr012',a:'transporte',ty:'flu',lv:3,ph:'Nos hemos pasado de parada',em:'😰'},
{id:'tr013',a:'transporte',ty:'flu',lv:3,ph:'Cómo se va a la plaza',em:'🗺️'},
{id:'tr014',a:'transporte',ty:'flu',lv:3,ph:'Estamos muy lejos todavía',em:'🗺️'},
{id:'tr015',a:'transporte',ty:'frases',lv:3,q:'¿Dónde está la parada del autobús?',fu:'Dónde está la parada del autobús',em:'🚏'},
{id:'tr016',a:'transporte',ty:'frases',lv:3,q:'¿Cuánto falta para llegar?',fu:'Cuánto falta para llegar',em:'⏰'},
{id:'tr017',a:'transporte',ty:'sit',lv:3,si:'No sabes cómo llegar',su:'Perdone cómo llego a la calle...',op:['Cómo llego a la calle...','Tengo hambre','Hola'],em:'🗺️'},
{id:'tr018',a:'transporte',ty:'sit',lv:3,si:'Hay muchos coches para cruzar',su:'Espera que el semáforo esté en verde',op:['Espera al semáforo verde','Cruzo corriendo','No sé'],em:'🚦'},
{id:'tr019',a:'transporte',ty:'flu',lv:4,ph:'Perdone este autobús va al centro',em:'🚌'},
{id:'tr020',a:'transporte',ty:'flu',lv:4,ph:'Me puede decir dónde me bajo',em:'🚌'},
{id:'tr021',a:'transporte',ty:'flu',lv:4,ph:'Perdone a qué hora sale el próximo autobús',em:'🚌'},
{id:'tr022',a:'transporte',ty:'flu',lv:4,ph:'Necesito un taxi para ir al hospital',em:'🚕'},
{id:'tr023',a:'transporte',ty:'frases',lv:4,q:'No sabes dónde bajar. ¿Qué preguntas?',fu:'Perdone me puede decir dónde me bajo',em:'🚌'},
{id:'tr024',a:'transporte',ty:'sit',lv:4,si:'Necesitas un taxi',su:'Necesito un taxi para ir al hospital',op:['Necesito un taxi al hospital','Quiero jugar','Adiós'],em:'🚕'},
{id:'tr025',a:'transporte',ty:'flu',lv:5,ph:'Perdone me puede decir cómo llego a la estación de autobuses',em:'🚏'},
{id:'tr026',a:'transporte',ty:'flu',lv:5,ph:'Nos hemos pasado de parada y no sé cómo volver',em:'😰'},

// 🍔 RESTAURANTE
{id:'re001',a:'restaurante',ty:'flu',lv:2,ph:'Quiero comer',em:'🍽️'},
{id:'re002',a:'restaurante',ty:'flu',lv:2,ph:'Quiero un zumo',em:'🧃'},
{id:'re003',a:'restaurante',ty:'flu',lv:2,ph:'La cuenta',em:'💶'},
{id:'re004',a:'restaurante',ty:'flu',lv:2,ph:'Más pan',em:'🍞'},
{id:'re005',a:'restaurante',ty:'flu',lv:2,ph:'Está bueno',em:'😋'},
{id:'re006',a:'restaurante',ty:'frases',lv:2,q:'Quieres pedir de beber. ¿Qué dices?',fu:'Quiero un zumo de naranja',em:'🧃'},
{id:'re007',a:'restaurante',ty:'flu',lv:3,ph:'Quiero una hamburguesa',em:'🍔'},
{id:'re008',a:'restaurante',ty:'flu',lv:3,ph:'Para mí unas patatas fritas',em:'🍟'},
{id:'re009',a:'restaurante',ty:'flu',lv:3,ph:'Sin cebolla por favor',em:'🧅'},
{id:'re010',a:'restaurante',ty:'flu',lv:3,ph:'Me pone un vaso de agua',em:'💧'},
{id:'re011',a:'restaurante',ty:'flu',lv:3,ph:'Dónde está el baño aquí',em:'🚻'},
{id:'re012',a:'restaurante',ty:'flu',lv:3,ph:'Esto no es lo que he pedido',em:'🔄'},
{id:'re013',a:'restaurante',ty:'flu',lv:3,ph:'Está muy bueno gracias',em:'😋'},
{id:'re014',a:'restaurante',ty:'flu',lv:3,ph:'Quiero un postre',em:'🍰'},
{id:'re015',a:'restaurante',ty:'flu',lv:3,ph:'Para mí una pizza',em:'🍕'},
{id:'re016',a:'restaurante',ty:'flu',lv:3,ph:'Sin tomate por favor',em:'🍅'},
{id:'re017',a:'restaurante',ty:'frases',lv:3,q:'¿Qué pides en un restaurante?',fu:'Yo quiero una hamburguesa con patatas',em:'🍔'},
{id:'re018',a:'restaurante',ty:'frases',lv:3,q:'No te gusta la cebolla. ¿Qué pides?',fu:'Sin cebolla por favor',em:'🧅'},
{id:'re019',a:'restaurante',ty:'sit',lv:3,si:'Quieres pedir en un restaurante',su:'Yo quiero una hamburguesa por favor',op:['Quiero una hamburguesa','Adiós','No sé'],em:'🍔'},
{id:'re020',a:'restaurante',ty:'sit',lv:3,si:'El camarero pregunta qué quieres beber',su:'Para mí un zumo de naranja',op:['Un zumo de naranja','No sé','Adiós'],em:'🧃'},
{id:'re021',a:'restaurante',ty:'sit',lv:3,si:'Has terminado de comer',su:'La cuenta por favor',op:['La cuenta por favor','Quiero más','No sé'],em:'💶'},
{id:'re022',a:'restaurante',ty:'flu',lv:4,ph:'Perdone me puede traer la carta',em:'📋'},
{id:'re023',a:'restaurante',ty:'flu',lv:4,ph:'Soy alérgico esto lleva gluten',em:'⚠️'},
{id:'re024',a:'restaurante',ty:'flu',lv:4,ph:'Me puede poner más pan por favor',em:'🍞'},
{id:'re025',a:'restaurante',ty:'flu',lv:4,ph:'Esto está frío me lo puede calentar',em:'🔥'},
{id:'re026',a:'restaurante',ty:'flu',lv:4,ph:'Queremos una mesa para cuatro',em:'🪑'},
{id:'re027',a:'restaurante',ty:'frases',lv:4,q:'Eres alérgico y quieres preguntar. ¿Qué dices?',fu:'Perdone esto lleva gluten soy alérgico',em:'⚠️'},
{id:'re028',a:'restaurante',ty:'sit',lv:4,si:'La comida está fría',su:'Perdone esto está frío me lo puede calentar',op:['Está frío me lo puede calentar','Vale','No importa'],em:'🔥'},
{id:'re029',a:'restaurante',ty:'flu',lv:5,ph:'Perdone quiero pedir una hamburguesa sin cebolla y un zumo de naranja',em:'🍔'},
{id:'re030',a:'restaurante',ty:'flu',lv:5,ph:'Esto no es lo que he pedido yo quería la hamburguesa sin cebolla',em:'🔄'},

// 🤝 RELACIONES
{id:'re001',a:'relaciones',ty:'flu',lv:1,ph:'Hola',em:'👋'},
{id:'re002',a:'relaciones',ty:'flu',lv:1,ph:'Adiós',em:'👋'},
{id:'re003',a:'relaciones',ty:'flu',lv:1,ph:'Gracias',em:'🙏'},
{id:'re004',a:'relaciones',ty:'flu',lv:1,ph:'Por favor',em:'🙏'},
{id:'re005',a:'relaciones',ty:'flu',lv:1,ph:'Perdona',em:'😔'},
{id:'re006',a:'relaciones',ty:'flu',lv:1,ph:'Sí',em:'✅'},
{id:'re007',a:'relaciones',ty:'flu',lv:1,ph:'No',em:'❌'},
{id:'re008',a:'relaciones',ty:'flu',lv:1,ph:'Te quiero',em:'❤️'},
{id:'re009',a:'relaciones',ty:'flu',lv:2,ph:'Hola qué tal',em:'👋'},
{id:'re010',a:'relaciones',ty:'flu',lv:2,ph:'Adiós hasta mañana',em:'👋'},
{id:'re011',a:'relaciones',ty:'flu',lv:2,ph:'Muchas gracias',em:'🙏'},
{id:'re012',a:'relaciones',ty:'flu',lv:2,ph:'Cómo te llamas',em:'👋'},
{id:'re013',a:'relaciones',ty:'flu',lv:2,ph:'Quieres ser mi amigo',em:'🤝'},
{id:'re014',a:'relaciones',ty:'flu',lv:2,ph:'Me llamo Guillermo',em:'👋'},
{id:'re015',a:'relaciones',ty:'flu',lv:2,ph:'Adiós hasta luego',em:'👋'},
{id:'re016',a:'relaciones',ty:'flu',lv:2,ph:'Buenos días',em:'🌅'},
{id:'re017',a:'relaciones',ty:'flu',lv:2,ph:'Buenas noches',em:'🌙'},
{id:'re018',a:'relaciones',ty:'flu',lv:2,ph:'Encantado de conocerte',em:'👋'},
{id:'re019',a:'relaciones',ty:'frases',lv:2,q:'Llegas a un sitio nuevo. ¿Qué dices?',fu:'Hola me llamo Guillermo',em:'👋'},
{id:'re020',a:'relaciones',ty:'frases',lv:2,q:'¿Cómo preguntas el nombre?',fu:'Hola cómo te llamas',em:'👋'},
{id:'re021',a:'relaciones',ty:'sit',lv:2,si:'Quieres jugar con alguien nuevo',su:'Quieres jugar conmigo',op:['Quieres jugar conmigo','Vete','Tengo sueño'],em:'⚽'},
{id:'re022',a:'relaciones',ty:'flu',lv:3,ph:'Muchas gracias eres muy amable',em:'🙏'},
{id:'re023',a:'relaciones',ty:'flu',lv:3,ph:'Perdona lo siento mucho',em:'😔'},
{id:'re024',a:'relaciones',ty:'flu',lv:3,ph:'Quedamos el sábado para jugar',em:'📅'},
{id:'re025',a:'relaciones',ty:'flu',lv:3,ph:'Te quiero mucho mamá',em:'❤️'},
{id:'re026',a:'relaciones',ty:'flu',lv:3,ph:'Me encanta jugar contigo',em:'😊'},
{id:'re027',a:'relaciones',ty:'flu',lv:3,ph:'Feliz cumpleaños te quiero',em:'🎂'},
{id:'re028',a:'relaciones',ty:'flu',lv:3,ph:'Eres mi mejor amigo',em:'🤝'},
{id:'re029',a:'relaciones',ty:'flu',lv:3,ph:'Puedo ir contigo',em:'🚶'},
{id:'re030',a:'relaciones',ty:'frases',lv:3,q:'Alguien te ayuda mucho. ¿Cómo le das las gracias?',fu:'Muchas gracias eres muy amable',em:'🙏'},
{id:'re031',a:'relaciones',ty:'frases',lv:3,q:'Has hecho algo mal. ¿Qué dices?',fu:'Perdona lo siento mucho',em:'😔'},
{id:'re032',a:'relaciones',ty:'frases',lv:3,q:'Es el cumpleaños de tu amigo. ¿Qué le dices?',fu:'Feliz cumpleaños te quiero mucho',em:'🎂'},
{id:'re033',a:'relaciones',ty:'sit',lv:3,si:'Tu amigo está triste',su:'Estás bien quieres hablar',op:['Estás bien quieres hablar','Me aburro','Adiós'],em:'😢'},
{id:'re034',a:'relaciones',ty:'sit',lv:3,si:'Quieres quedar con un amigo',su:'Quedamos el sábado para jugar',op:['Quedamos el sábado','No sé','Adiós'],em:'📅'},
{id:'re035',a:'relaciones',ty:'sit',lv:3,si:'Es el cumpleaños de tu amigo',su:'Feliz cumpleaños te quiero mucho',op:['Feliz cumpleaños te quiero','Adiós','No sé'],em:'🎂'},
{id:'re036',a:'relaciones',ty:'flu',lv:4,ph:'Me alegro mucho de verte otra vez',em:'😊'},
{id:'re037',a:'relaciones',ty:'flu',lv:4,ph:'Eso que has dicho me ha molestado',em:'😠'},
{id:'re038',a:'relaciones',ty:'flu',lv:4,ph:'Te echo mucho de menos cuando no estás',em:'😔'},
{id:'re039',a:'relaciones',ty:'flu',lv:4,ph:'No pasa nada pero no lo hagas más',em:'🤝'},
{id:'re040',a:'relaciones',ty:'frases',lv:4,q:'Un amigo ha dicho algo feo. ¿Cómo se lo dices?',fu:'Eso que has dicho me ha molestado',em:'😠'},
{id:'re041',a:'relaciones',ty:'sit',lv:4,si:'Un amigo te pide perdón',su:'No pasa nada pero no lo hagas más',op:['No pasa nada pero no lo hagas más','Vete','Me da igual'],em:'🤝'},
{id:'re042',a:'relaciones',ty:'sit',lv:4,si:'Tu amigo te ha mentido',su:'Me has mentido y eso me duele',op:['Me has mentido y me duele','No pasa nada','Me da igual'],em:'💔'},
{id:'re043',a:'relaciones',ty:'flu',lv:5,ph:'No estoy de acuerdo contigo pero te respeto',em:'🤝'},
{id:'re044',a:'relaciones',ty:'frases',lv:5,q:'Piensas diferente a tu amigo. ¿Qué dices?',fu:'No estoy de acuerdo contigo pero te respeto',em:'🤝'},
{id:'re045',a:'relaciones',ty:'flu',lv:5,ph:'Quiero darte las gracias por todo lo que haces por mí',em:'🙏'},

// 💛 SENTIMIENTOS
{id:'se001',a:'sentimientos',ty:'flu',lv:1,ph:'Estoy bien',em:'😊'},
{id:'se002',a:'sentimientos',ty:'flu',lv:1,ph:'Estoy triste',em:'😢'},
{id:'se003',a:'sentimientos',ty:'flu',lv:1,ph:'Estoy contento',em:'😊'},
{id:'se004',a:'sentimientos',ty:'flu',lv:1,ph:'Tengo miedo',em:'😨'},
{id:'se005',a:'sentimientos',ty:'flu',lv:1,ph:'Estoy enfadado',em:'😠'},
{id:'se006',a:'sentimientos',ty:'flu',lv:1,ph:'Estoy cansado',em:'😫'},
{id:'se007',a:'sentimientos',ty:'flu',lv:2,ph:'Estoy muy contento',em:'😊'},
{id:'se008',a:'sentimientos',ty:'flu',lv:2,ph:'Estoy muy triste',em:'😢'},
{id:'se009',a:'sentimientos',ty:'flu',lv:2,ph:'Estoy muy cansado',em:'😫'},
{id:'se010',a:'sentimientos',ty:'flu',lv:2,ph:'Estoy aburrido',em:'😐'},
{id:'se011',a:'sentimientos',ty:'flu',lv:2,ph:'Estoy nervioso',em:'😰'},
{id:'se012',a:'sentimientos',ty:'flu',lv:2,ph:'Estoy asustado',em:'😨'},
{id:'se013',a:'sentimientos',ty:'flu',lv:2,ph:'Me siento solo',em:'😔'},
{id:'se014',a:'sentimientos',ty:'flu',lv:2,ph:'Estoy preocupado',em:'😟'},
{id:'se015',a:'sentimientos',ty:'flu',lv:2,ph:'Estoy sorprendido',em:'😮'},
{id:'se016',a:'sentimientos',ty:'frases',lv:2,q:'¿Cómo te encuentras hoy?',fu:'Estoy muy contento hoy',em:'😊'},
{id:'se017',a:'sentimientos',ty:'frases',lv:2,q:'Estás triste. ¿Qué dices?',fu:'Estoy triste hoy',em:'😢'},
{id:'se018',a:'sentimientos',ty:'flu',lv:3,ph:'Tengo miedo no me gusta esto',em:'😨'},
{id:'se019',a:'sentimientos',ty:'flu',lv:3,ph:'Estoy triste porque no puedo ir',em:'😢'},
{id:'se020',a:'sentimientos',ty:'flu',lv:3,ph:'Me hace mucha ilusión',em:'🤩'},
{id:'se021',a:'sentimientos',ty:'flu',lv:3,ph:'Estoy feliz porque es mi cumpleaños',em:'🎂'},
{id:'se022',a:'sentimientos',ty:'flu',lv:3,ph:'Estoy contento mi equipo ha ganado',em:'🏆'},
{id:'se023',a:'sentimientos',ty:'flu',lv:3,ph:'No me apetece hacer eso',em:'😐'},
{id:'se024',a:'sentimientos',ty:'flu',lv:3,ph:'Estoy harto de esperar',em:'😤'},
{id:'se025',a:'sentimientos',ty:'frases',lv:3,q:'Algo te hace mucha ilusión. ¿Qué dices?',fu:'Estoy muy contento me hace mucha ilusión',em:'🤩'},
{id:'se026',a:'sentimientos',ty:'frases',lv:3,q:'Es tu cumpleaños y estás feliz. ¿Qué dices?',fu:'Estoy feliz porque hoy es mi cumpleaños',em:'🎂'},
{id:'se027',a:'sentimientos',ty:'sit',lv:3,si:'Alguien rompe tu juguete',su:'Estoy triste porque has roto mi juguete',op:['Estoy triste','Gracias','Me da igual'],em:'💔'},
{id:'se028',a:'sentimientos',ty:'sit',lv:3,si:'Tu equipo favorito ha ganado',su:'Estoy muy contento mi equipo ha ganado',op:['Estoy contento mi equipo ha ganado','Normal','Me da igual'],em:'🏆'},
{id:'se029',a:'sentimientos',ty:'flu',lv:4,ph:'Estoy enfadado porque no es justo',em:'😠'},
{id:'se030',a:'sentimientos',ty:'flu',lv:4,ph:'Me siento solo y quiero estar con alguien',em:'😔'},
{id:'se031',a:'sentimientos',ty:'flu',lv:4,ph:'Cuando me gritan me siento muy mal',em:'😢'},
{id:'se032',a:'sentimientos',ty:'flu',lv:4,ph:'Estoy orgulloso de mi nota',em:'💪'},
{id:'se033',a:'sentimientos',ty:'frases',lv:4,q:'Algo no es justo. ¿Qué dices?',fu:'Estoy enfadado porque no es justo',em:'😠'},
{id:'se034',a:'sentimientos',ty:'frases',lv:4,q:'Alguien te grita. ¿Qué dices?',fu:'Cuando me gritas me siento muy mal',em:'😢'},
{id:'se035',a:'sentimientos',ty:'sit',lv:4,si:'Has sacado buena nota',su:'Estoy muy orgulloso de mi nota',op:['Estoy muy orgulloso','Normal','No sé'],em:'💪'},
{id:'se036',a:'sentimientos',ty:'flu',lv:5,ph:'Me siento orgulloso de lo que he hecho',em:'💪'},
{id:'se037',a:'sentimientos',ty:'flu',lv:5,ph:'Estoy nervioso porque mañana tengo algo importante',em:'😰'},
{id:'se038',a:'sentimientos',ty:'frases',lv:5,q:'Has hecho algo genial. ¿Qué dices?',fu:'Me siento orgulloso de lo que he hecho',em:'💪'},

// 📚 COLEGIO
{id:'co001',a:'colegio',ty:'flu',lv:1,ph:'No entiendo',em:'❓'},
{id:'co002',a:'colegio',ty:'flu',lv:1,ph:'Otra vez',em:'🔄'},
{id:'co003',a:'colegio',ty:'flu',lv:1,ph:'Ya está',em:'✅'},
{id:'co004',a:'colegio',ty:'flu',lv:1,ph:'No sé',em:'🤷'},
{id:'co005',a:'colegio',ty:'flu',lv:1,ph:'Puedo ir',em:'❓'},
{id:'co006',a:'colegio',ty:'flu',lv:2,ph:'No lo entiendo',em:'❓'},
{id:'co007',a:'colegio',ty:'flu',lv:2,ph:'Me ayudas',em:'🙋'},
{id:'co008',a:'colegio',ty:'flu',lv:2,ph:'He terminado',em:'✅'},
{id:'co009',a:'colegio',ty:'flu',lv:2,ph:'Necesito un lápiz',em:'✏️'},
{id:'co010',a:'colegio',ty:'flu',lv:2,ph:'Puedo ir al baño',em:'🚻'},
{id:'co011',a:'colegio',ty:'flu',lv:2,ph:'Dónde es la clase',em:'📚'},
{id:'co012',a:'colegio',ty:'flu',lv:2,ph:'Se me ha olvidado',em:'😅'},
{id:'co013',a:'colegio',ty:'flu',lv:2,ph:'No tengo libro',em:'📖'},
{id:'co014',a:'colegio',ty:'frases',lv:2,q:'No entiendes algo. ¿Qué dices?',fu:'No lo entiendo me lo explicas',em:'❓'},
{id:'co015',a:'colegio',ty:'frases',lv:2,q:'Necesitas ir al baño. ¿Qué dices?',fu:'Puedo ir al baño por favor',em:'🚻'},
{id:'co016',a:'colegio',ty:'sit',lv:2,si:'No entiendes lo que dice el profesor',su:'Perdona no lo entiendo',op:['Perdona no lo entiendo','Me da igual','Adiós'],em:'❓'},
{id:'co017',a:'colegio',ty:'flu',lv:3,ph:'No entiendo esto me lo explicas',em:'❓'},
{id:'co018',a:'colegio',ty:'flu',lv:3,ph:'He terminado el ejercicio',em:'✅'},
{id:'co019',a:'colegio',ty:'flu',lv:3,ph:'Se me ha roto el lápiz',em:'✏️'},
{id:'co020',a:'colegio',ty:'flu',lv:3,ph:'Puedo ir al baño por favor',em:'🚻'},
{id:'co021',a:'colegio',ty:'flu',lv:3,ph:'Se me ha olvidado el libro',em:'📖'},
{id:'co022',a:'colegio',ty:'flu',lv:3,ph:'Perdona he llegado tarde',em:'⏰'},
{id:'co023',a:'colegio',ty:'flu',lv:3,ph:'Puedo sentarme con él',em:'🪑'},
{id:'co024',a:'colegio',ty:'flu',lv:3,ph:'No me sale este problema',em:'📝'},
{id:'co025',a:'colegio',ty:'frases',lv:3,q:'Has terminado el ejercicio. ¿Qué dices?',fu:'He terminado el ejercicio profe',em:'✅'},
{id:'co026',a:'colegio',ty:'frases',lv:3,q:'Se te ha olvidado el libro. ¿Qué dices?',fu:'Se me ha olvidado el libro en casa',em:'📖'},
{id:'co027',a:'colegio',ty:'sit',lv:3,si:'No te sale un problema de mates',su:'No me sale este problema me ayudas',op:['No me sale me ayudas','Me da igual','Adiós'],em:'📝'},
{id:'co028',a:'colegio',ty:'sit',lv:3,si:'Un compañero te molesta en clase',su:'Para de molestarme por favor',op:['Para de molestarme','Vale','No pasa nada'],em:'😠'},
{id:'co029',a:'colegio',ty:'sit',lv:3,si:'Llegas tarde a clase',su:'Perdona profe he llegado tarde',op:['Perdona he llegado tarde','Hola','No sé'],em:'⏰'},
{id:'co030',a:'colegio',ty:'flu',lv:4,ph:'Perdona profe no he traído los deberes',em:'📝'},
{id:'co031',a:'colegio',ty:'flu',lv:4,ph:'Me puede repetir eso no lo he entendido',em:'❓'},
{id:'co032',a:'colegio',ty:'flu',lv:4,ph:'Puedo cambiarme de sitio por favor',em:'🪑'},
{id:'co033',a:'colegio',ty:'flu',lv:4,ph:'No me encuentro bien puedo ir a enfermería',em:'🏥'},
{id:'co034',a:'colegio',ty:'frases',lv:4,q:'No has traído los deberes. ¿Qué dices?',fu:'Perdona profe no he traído los deberes',em:'📝'},
{id:'co035',a:'colegio',ty:'sit',lv:4,si:'Te sientes mal en clase',su:'No me encuentro bien puedo ir a enfermería',op:['Puedo ir a enfermería','Estoy bien','No sé'],em:'🏥'},
{id:'co036',a:'colegio',ty:'flu',lv:5,ph:'Perdona profe no he traído los deberes porque ayer me encontraba mal',em:'📝'},
{id:'co037',a:'colegio',ty:'flu',lv:5,ph:'No entiendo este problema me lo puedes explicar de otra manera',em:'❓'},

// 🎮 OCIO
{id:'oc001',a:'ocio',ty:'flu',lv:1,ph:'Quiero jugar',em:'🎮'},
{id:'oc002',a:'ocio',ty:'flu',lv:1,ph:'Me gusta',em:'👍'},
{id:'oc003',a:'ocio',ty:'flu',lv:1,ph:'No me gusta',em:'👎'},
{id:'oc004',a:'ocio',ty:'flu',lv:1,ph:'Otra vez',em:'🔄'},
{id:'oc005',a:'ocio',ty:'flu',lv:1,ph:'Más',em:'➕'},
{id:'oc006',a:'ocio',ty:'flu',lv:2,ph:'Quiero jugar un rato',em:'🎮'},
{id:'oc007',a:'ocio',ty:'flu',lv:2,ph:'Me gusta mucho esto',em:'👍'},
{id:'oc008',a:'ocio',ty:'flu',lv:2,ph:'Puedo ver la tele',em:'📺'},
{id:'oc009',a:'ocio',ty:'flu',lv:2,ph:'Quiero pintar',em:'🎨'},
{id:'oc010',a:'ocio',ty:'flu',lv:2,ph:'Puedo ver un vídeo',em:'📱'},
{id:'oc011',a:'ocio',ty:'flu',lv:2,ph:'Vamos al parque',em:'🌳'},
{id:'oc012',a:'ocio',ty:'flu',lv:2,ph:'Quiero escuchar música',em:'🎵'},
{id:'oc013',a:'ocio',ty:'flu',lv:2,ph:'Quiero nadar',em:'🏊'},
{id:'oc014',a:'ocio',ty:'frases',lv:2,q:'Quieres jugar un rato. ¿Qué dices?',fu:'Quiero jugar un rato',em:'🎮'},
{id:'oc015',a:'ocio',ty:'frases',lv:2,q:'Quieres ver una película. ¿Qué dices?',fu:'Podemos ver una película',em:'🎬'},
{id:'oc016',a:'ocio',ty:'flu',lv:3,ph:'Puedo jugar al Minecraft un rato',em:'⛏️'},
{id:'oc017',a:'ocio',ty:'flu',lv:3,ph:'Me gusta mucho el fútbol',em:'⚽'},
{id:'oc018',a:'ocio',ty:'flu',lv:3,ph:'Quiero ir al parque a jugar',em:'🌳'},
{id:'oc019',a:'ocio',ty:'flu',lv:3,ph:'Vamos a jugar al balón',em:'⚽'},
{id:'oc020',a:'ocio',ty:'flu',lv:3,ph:'Puedo poner mi canción favorita',em:'🎵'},
{id:'oc021',a:'ocio',ty:'flu',lv:3,ph:'Me gusta mucho dibujar',em:'🎨'},
{id:'oc022',a:'ocio',ty:'flu',lv:3,ph:'Quiero ir a la piscina',em:'🏊'},
{id:'oc023',a:'ocio',ty:'flu',lv:3,ph:'Vamos a montar en bici',em:'🚲'},
{id:'oc024',a:'ocio',ty:'frases',lv:3,q:'Quieres ir al parque. ¿Qué dices?',fu:'Podemos ir al parque a jugar',em:'🌳'},
{id:'oc025',a:'ocio',ty:'frases',lv:3,q:'Quieres escuchar tu canción. ¿Qué dices?',fu:'Puedo poner mi canción favorita',em:'🎵'},
{id:'oc026',a:'ocio',ty:'sit',lv:3,si:'Quieres jugar al Minecraft',su:'Puedo jugar al Minecraft un rato',op:['Puedo jugar al Minecraft','No quiero','Estoy mal'],em:'⛏️'},
{id:'oc027',a:'ocio',ty:'sit',lv:3,si:'Tu amigo pregunta qué te gusta',su:'Me gusta mucho jugar al fútbol',op:['Me gusta jugar al fútbol','No sé','Adiós'],em:'⚽'},
{id:'oc028',a:'ocio',ty:'sit',lv:3,si:'Quieres escuchar música',su:'Puedo poner música un rato',op:['Puedo poner música','No quiero','Tengo sueño'],em:'🎵'},
{id:'oc029',a:'ocio',ty:'flu',lv:4,ph:'Este fin de semana quiero ir a la piscina',em:'🏊'},
{id:'oc030',a:'ocio',ty:'flu',lv:4,ph:'Ayer fui al parque con mi familia',em:'🌳'},
{id:'oc031',a:'ocio',ty:'flu',lv:4,ph:'El otro día vi una película muy divertida',em:'🎬'},
{id:'oc032',a:'ocio',ty:'flu',lv:4,ph:'Me gustaría aprender a tocar la guitarra',em:'🎸'},
{id:'oc033',a:'ocio',ty:'frases',lv:4,q:'Tu amigo pregunta qué hiciste ayer. ¿Qué dices?',fu:'Ayer fui al parque con mi familia',em:'🌳'},
{id:'oc034',a:'ocio',ty:'sit',lv:4,si:'Un amigo pregunta qué hiciste el finde',su:'Fui al parque con mi familia y lo pasé genial',op:['Fui al parque con mi familia','No sé','Adiós'],em:'🌳'},
{id:'oc035',a:'ocio',ty:'sit',lv:4,si:'Un amigo te pregunta qué música te gusta',su:'Me gusta mucho la música de...',op:['Me gusta mucho la música','No sé','Adiós'],em:'🎵'},
{id:'oc036',a:'ocio',ty:'flu',lv:5,ph:'Lo que más me gusta del mundo es jugar al fútbol con mis amigos',em:'⚽'},
{id:'oc037',a:'ocio',ty:'frases',lv:5,q:'¿Qué es lo que más te gusta hacer?',fu:'Lo que más me gusta es jugar con mis amigos',em:'⚽'},

// 📱 TECNOLOGÍA
{id:'te001',a:'tecnologia',ty:'flu',lv:1,ph:'No funciona',em:'📱'},
{id:'te002',a:'tecnologia',ty:'flu',lv:1,ph:'Se ha roto',em:'💔'},
{id:'te003',a:'tecnologia',ty:'flu',lv:1,ph:'No hay wifi',em:'📶'},
{id:'te004',a:'tecnologia',ty:'flu',lv:1,ph:'Está apagado',em:'🔌'},
{id:'te005',a:'tecnologia',ty:'flu',lv:2,ph:'No me funciona',em:'📱'},
{id:'te006',a:'tecnologia',ty:'flu',lv:2,ph:'Se ha quedado sin batería',em:'🔋'},
{id:'te007',a:'tecnologia',ty:'flu',lv:2,ph:'No hay internet',em:'📶'},
{id:'te008',a:'tecnologia',ty:'flu',lv:2,ph:'Quiero ver un vídeo',em:'📱'},
{id:'te009',a:'tecnologia',ty:'flu',lv:2,ph:'Puedo usar la tablet',em:'📱'},
{id:'te010',a:'tecnologia',ty:'flu',lv:2,ph:'La tele no funciona',em:'📺'},
{id:'te011',a:'tecnologia',ty:'flu',lv:2,ph:'Se ha bloqueado',em:'🔒'},
{id:'te012',a:'tecnologia',ty:'frases',lv:2,q:'La tablet no funciona. ¿Qué dices?',fu:'La tablet no me funciona',em:'📱'},
{id:'te013',a:'tecnologia',ty:'frases',lv:2,q:'Necesitas cargar el móvil. ¿Qué dices?',fu:'Se ha quedado sin batería',em:'🔋'},
{id:'te014',a:'tecnologia',ty:'sit',lv:2,si:'No te funciona la tablet',su:'No me funciona la tablet',op:['No me funciona la tablet','Me da igual','Adiós'],em:'📱'},
{id:'te015',a:'tecnologia',ty:'flu',lv:3,ph:'No me carga el móvil',em:'🔋'},
{id:'te016',a:'tecnologia',ty:'flu',lv:3,ph:'Se me ha caído la tablet',em:'📱'},
{id:'te017',a:'tecnologia',ty:'flu',lv:3,ph:'No puedo entrar en internet',em:'📶'},
{id:'te018',a:'tecnologia',ty:'flu',lv:3,ph:'Quiero llamar a mi amigo',em:'📞'},
{id:'te019',a:'tecnologia',ty:'flu',lv:3,ph:'Me puedes poner el wifi',em:'📶'},
{id:'te020',a:'tecnologia',ty:'flu',lv:3,ph:'Esta app no me funciona',em:'📱'},
{id:'te021',a:'tecnologia',ty:'flu',lv:3,ph:'Necesito el cargador del móvil',em:'🔌'},
{id:'te022',a:'tecnologia',ty:'frases',lv:3,q:'No hay wifi. ¿Qué dices?',fu:'No hay wifi me puedes conectar',em:'📶'},
{id:'te023',a:'tecnologia',ty:'frases',lv:3,q:'Se te ha caído la tablet. ¿Qué dices?',fu:'Se me ha caído la tablet al suelo',em:'📱'},
{id:'te024',a:'tecnologia',ty:'sit',lv:3,si:'Se te ha acabado la batería',su:'Necesito cargar el móvil se ha quedado sin batería',op:['Necesito cargar el móvil','Me da igual','Adiós'],em:'🔋'},
{id:'te025',a:'tecnologia',ty:'sit',lv:3,si:'Quieres hacer una llamada',su:'Puedo usar el teléfono para llamar a mi amigo',op:['Puedo usar el teléfono','No quiero','Adiós'],em:'📞'},
{id:'te026',a:'tecnologia',ty:'flu',lv:4,ph:'Se me ha caído el móvil al agua y no funciona',em:'📱'},
{id:'te027',a:'tecnologia',ty:'flu',lv:4,ph:'Necesito el cargador del móvil se ha quedado sin batería',em:'🔌'},
{id:'te028',a:'tecnologia',ty:'flu',lv:4,ph:'Me puedes ayudar que no sé cómo funciona esto',em:'❓'},
{id:'te029',a:'tecnologia',ty:'frases',lv:4,q:'La app no funciona. ¿Qué dices?',fu:'Esta app no funciona me puedes ayudar',em:'📱'},
{id:'te030',a:'tecnologia',ty:'sit',lv:4,si:'No sabes usar algo en el móvil',su:'Me puedes enseñar cómo se hace esto',op:['Me puedes enseñar','No sé','Me da igual'],em:'📱'},
{id:'te031',a:'tecnologia',ty:'flu',lv:5,ph:'Se me ha caído el móvil al suelo y ahora la pantalla está rota no funciona bien',em:'📱'},

// 🏠 CASA
{id:'ca001',a:'casa',ty:'flu',lv:1,ph:'Ya está',em:'✅'},
{id:'ca002',a:'casa',ty:'flu',lv:1,ph:'Listo',em:'✅'},
{id:'ca003',a:'casa',ty:'flu',lv:1,ph:'Ayúdame',em:'🙋'},
{id:'ca004',a:'casa',ty:'flu',lv:1,ph:'Dónde está',em:'❓'},
{id:'ca005',a:'casa',ty:'flu',lv:1,ph:'Es mío',em:'🚫'},
{id:'ca006',a:'casa',ty:'flu',lv:2,ph:'Ya he terminado',em:'✅'},
{id:'ca007',a:'casa',ty:'flu',lv:2,ph:'Dónde están mis cosas',em:'❓'},
{id:'ca008',a:'casa',ty:'flu',lv:2,ph:'Voy a mi cuarto',em:'🛏️'},
{id:'ca009',a:'casa',ty:'flu',lv:2,ph:'Quiero ver la tele',em:'📺'},
{id:'ca010',a:'casa',ty:'flu',lv:2,ph:'Quién es',em:'🚪'},
{id:'ca011',a:'casa',ty:'flu',lv:2,ph:'Puedo abrir',em:'🚪'},
{id:'ca012',a:'casa',ty:'flu',lv:2,ph:'Ya me he vestido',em:'👕'},
{id:'ca013',a:'casa',ty:'flu',lv:2,ph:'Ya me he lavado',em:'🧼'},
{id:'ca014',a:'casa',ty:'frases',lv:2,q:'Has terminado de recoger. ¿Qué dices?',fu:'Ya he terminado todo',em:'✅'},
{id:'ca015',a:'casa',ty:'frases',lv:2,q:'No encuentras tus cosas. ¿Qué dices?',fu:'Dónde están mis cosas',em:'❓'},
{id:'ca016',a:'casa',ty:'sit',lv:2,si:'Llaman a la puerta',su:'Quién es',op:['Quién es','Paso','Adiós'],em:'🚪'},
{id:'ca017',a:'casa',ty:'flu',lv:3,ph:'Voy a recoger mi habitación',em:'🛏️'},
{id:'ca018',a:'casa',ty:'flu',lv:3,ph:'Ya he hecho los deberes',em:'📝'},
{id:'ca019',a:'casa',ty:'flu',lv:3,ph:'Puedo bajar al parque un rato',em:'🌳'},
{id:'ca020',a:'casa',ty:'flu',lv:3,ph:'Me voy a duchar ahora',em:'🚿'},
{id:'ca021',a:'casa',ty:'flu',lv:3,ph:'He puesto la mesa',em:'🍽️'},
{id:'ca022',a:'casa',ty:'flu',lv:3,ph:'Ya he recogido mi cuarto',em:'🛏️'},
{id:'ca023',a:'casa',ty:'flu',lv:3,ph:'Puedo quedarme despierto un rato',em:'😴'},
{id:'ca024',a:'casa',ty:'flu',lv:3,ph:'Me he lavado las manos',em:'🧼'},
{id:'ca025',a:'casa',ty:'frases',lv:3,q:'Has hecho los deberes. ¿Qué dices?',fu:'Ya he hecho los deberes',em:'📝'},
{id:'ca026',a:'casa',ty:'frases',lv:3,q:'Quieres bajar al parque. ¿Qué dices?',fu:'Puedo bajar al parque un rato',em:'🌳'},
{id:'ca027',a:'casa',ty:'sit',lv:3,si:'Tu madre te pide recoger el cuarto',su:'Voy a recoger mi habitación ahora',op:['Voy a recoger','No quiero','Luego'],em:'🛏️'},
{id:'ca028',a:'casa',ty:'sit',lv:3,si:'Es hora de cenar y no has puesto la mesa',su:'Ahora pongo la mesa',op:['Ahora pongo la mesa','No quiero','Luego'],em:'🍽️'},
{id:'ca029',a:'casa',ty:'sit',lv:3,si:'Es hora de dormir y quieres quedarte',su:'Puedo quedarme un ratito más',op:['Puedo quedarme un ratito','No quiero dormir','Adiós'],em:'😴'},
{id:'ca030',a:'casa',ty:'flu',lv:4,ph:'Ya he recogido mi cuarto y he hecho los deberes',em:'📝'},
{id:'ca031',a:'casa',ty:'flu',lv:4,ph:'Me puedes dejar quedarme despierto un rato más',em:'😴'},
{id:'ca032',a:'casa',ty:'flu',lv:4,ph:'Necesito que me ayudes con los deberes de mates',em:'📝'},
{id:'ca033',a:'casa',ty:'flu',lv:4,ph:'He puesto la lavadora como me has dicho',em:'🧺'},
{id:'ca034',a:'casa',ty:'frases',lv:4,q:'Necesitas ayuda con los deberes. ¿Qué dices?',fu:'Necesito que me ayudes con los deberes',em:'📝'},
{id:'ca035',a:'casa',ty:'sit',lv:4,si:'Has hecho todas tus tareas',su:'Ya he recogido y he hecho los deberes puedo jugar',op:['Ya he terminado todo puedo jugar','No quiero','Adiós'],em:'✅'},
{id:'ca036',a:'casa',ty:'flu',lv:5,ph:'Ya he terminado de recoger mi cuarto y de hacer los deberes puedo jugar un rato',em:'✅'},
{id:'ca037',a:'casa',ty:'flu',lv:5,ph:'Mañana necesito llevar el chándal al cole porque tenemos educación física',em:'🏃'},
];